services:
  _defaults:
    autowire: true
    autoconfigure: true

  Swoopde\ContaoNextPrevPageimageBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'

  Swoopde\ContaoNextPrevPageimageBundle\Twig\ContaoVersionExtension:
    tags: [ 'twig.extension' ]
